CREATE TABLE IF NOT EXISTS "doctors"(
  "D_ID" TEXT,
  "D_NAME" TEXT,
  "D_GENDER" TEXT,
  "D_AGE" TEXT,
  "D_SPECIALIZATION" TEXT,
  "D_YEARS_OF_EXPERIENCE" TEXT,
  "D_CONTACT" TEXT,
  "D_STREET" TEXT,
  "D_CITY" TEXT
);
CREATE TABLE IF NOT EXISTS "instruments"(
  "I_ID" TEXT,
  "I_NAME" TEXT,
  "I_MANUFACTURER" TEXT
);
CREATE TABLE IF NOT EXISTS "n_assists"(
  "N_ID" TEXT,
  "D_ID" TEXT
);
CREATE TABLE IF NOT EXISTS "nurses"(
  "N_ID" TEXT,
  "N_NAME" TEXT,
  "N_SPECIALIZATION" TEXT,
  "N_SHIFT" TEXT,
  "N_STREET" TEXT,
  "N_CITY" TEXT
);
CREATE TABLE IF NOT EXISTS "p_assignment"(
  "P_ID" TEXT,
  "D_ID" TEXT
);
CREATE TABLE IF NOT EXISTS "patients"(
  "P_ID" TEXT,
  "P_NAME" TEXT,
  "P_GENDER" TEXT,
  "P_AGE" TEXT,
  "P_DISEASE" TEXT,
  "P_CONTACT" TEXT,
  "P_STREET" TEXT,
  "P_CITY" TEXT
);
CREATE TABLE IF NOT EXISTS "tests"(
  "T_ID" TEXT,
  "T_NAME" TEXT,
  "P_ID" TEXT,
  "D_ID" TEXT,
  "I_ID" TEXT,
  "T_DATE" TEXT,
  "T_RESULT" TEXT
);
